// Firebase configuration for the `newpower-bgx` project.
//
// Normally generated by `flutterfire configure`, which needs network access
// to the Firebase API. Written by hand from the two config files already in
// the repo, so the values are the same ones the native SDKs read:
//
//   Android → android/app/google-services.json
//   iOS     → ios/Runner/GoogleService-Info.plist
//
// ⚠️ Keep this file in step with those two. Android and iOS actually read
// the native files (via the google-services Gradle plugin and the bundled
// plist); this class is what `Firebase.initializeApp` uses on the Dart side,
// so a mismatch shows up as a working native build with a Dart-side app that
// talks to the wrong project.
//
// These keys are **not secrets** — a Firebase API key identifies the
// project, it does not authorise anything on its own; access is governed by
// the backend's own auth. They ship inside every distributed app binary by
// design.
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'NewPower has no web target — no web app is registered in the '
        'Firebase project, so there is nothing to return here.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        // Desktop targets are not registered in the Firebase project. The
        // app still runs there; push simply never initialises, which
        // `PushService` treats as "push unavailable" rather than an error.
        throw UnsupportedError(
          'No Firebase app is registered for $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmemC33trUPQqhgf2JKW-Z-f1SvSfULt8',
    appId: '1:141224916519:android:ee6e085e683cdeeb538002',
    messagingSenderId: '141224916519',
    projectId: 'newpower-bgx',
    storageBucket: 'newpower-bgx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARCDDmb1GeZeJt2OkNvN5iy-iqxPnA4Zo',
    appId: '1:141224916519:ios:f4db093176574bb4538002',
    messagingSenderId: '141224916519',
    projectId: 'newpower-bgx',
    storageBucket: 'newpower-bgx.firebasestorage.app',
    // Must equal PRODUCT_BUNDLE_IDENTIFIER in Runner.xcodeproj and BUNDLE_ID
    // in GoogleService-Info.plist. All three read com.newpower.app, which
    // also matches the Android applicationId.
    iosBundleId: 'com.newpower.app',
  );
}
